In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import svm
import cv2
import csv

In [2]:
plt.style.use('seaborn')

In [3]:
data = pd.read_csv('Train/train.csv')
df = np.array(data)

In [4]:
labels = []
m = df.shape[0]

for i in range(m):
    labels.append(df[i][1])


In [5]:
data.head()

ImageId NameOfPokemon
0  296.jpg       Pikachu
1  297.jpg       Pikachu
2  298.jpg       Pikachu
3  299.jpg       Pikachu
4  300.jpg       Pikachu

In [6]:
# print(df)

In [7]:
datapath = "Train/Images/"

def create_data(df):
    m = df.shape[0]
    X = []
    for i in range(m):
        img = cv2.imread(datapath+df[i][0])
#         print(datapath+df[i][0])
        img = cv2.resize(img,(300,300))
        X.append(img)
    return X

In [8]:
X = create_data(df)

In [9]:
# X

In [10]:
type(X)

list

In [11]:
# X

In [12]:
X = np.array(X)

In [13]:
X.shape

(304, 300, 300, 3)

In [14]:
X = X.reshape((X.shape[0],-1))

In [15]:
X.shape

(304, 270000)

In [16]:
def normalize(X):
    m = X.shape[0]
    for i in range(m):
        u = np.mean(X[i])
        sigma = np.std(X[i])
        X[i] = (X[i] - u)/sigma
    return X

In [17]:
X = normalize(X)

In [18]:
print(X)

[[  1   0   0 ...   0   0 255]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [19]:
X

array([[  1,   0,   0, ...,   0,   0, 255],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)

In [20]:
from sklearn import svm

In [21]:
svm_classifier = svm.SVC(kernel='linear',C=1.0)

In [22]:
svm_classifier.fit(X,labels)
svm_classifier.score(X,labels)

1.0

In [23]:
test_data = pd.read_csv('Test/test.csv')
test = np.array(test_data)

In [24]:
test_data.head()

ImageId
0  1106.jpg
1  2236.jpg
2  1131.jpg
3  2221.jpg
4  2011.jpg

In [25]:
# print(test)

In [26]:
dp = "Test/Images/"

def create_data(test):
    n = test.shape[0]
    x = []
    for i in range(n):
        t_img = cv2.imread(dp+test[i][0])
#         print(dp+test[i][0])
        t_img = cv2.resize(t_img,(300,300))
        x.append(t_img)
    return x

In [27]:
x = create_data(test)

In [28]:
# x

In [29]:
x = np.array(x)

In [30]:
x.shape

(123, 300, 300, 3)

In [31]:
x = x.reshape((x.shape[0],-1))

In [32]:
x.shape

(123, 270000)

In [33]:
x = normalize(x)

In [34]:
print(x)

[[  1   1   1 ...   1   1   1]
 [  0   0   0 ...   0   0   0]
 [  1   1   1 ...   1   1   1]
 ...
 [  0   0   0 ...   0   0   0]
 [255   0 254 ... 255   1   0]
 [  1   1   1 ...   1   1   1]]


In [35]:
x

array([[  1,   1,   1, ...,   1,   1,   1],
       [  0,   0,   0, ...,   0,   0,   0],
       [  1,   1,   1, ...,   1,   1,   1],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [255,   0, 254, ..., 255,   1,   0],
       [  1,   1,   1, ...,   1,   1,   1]], dtype=uint8)

In [36]:
lab = svm_classifier.predict(x)

In [37]:
print(lab)

['Bulbasaur' 'Charmander' 'Bulbasaur' 'Charmander' 'Bulbasaur' 'Bulbasaur'
 'Charmander' 'Bulbasaur' 'Bulbasaur' 'Charmander' 'Bulbasaur' 'Bulbasaur'
 'Bulbasaur' 'Bulbasaur' 'Charmander' 'Pikachu' 'Charmander' 'Charmander'
 'Pikachu' 'Charmander' 'Pikachu' 'Bulbasaur' 'Charmander' 'Bulbasaur'
 'Pikachu' 'Charmander' 'Bulbasaur' 'Bulbasaur' 'Pikachu' 'Pikachu'
 'Charmander' 'Bulbasaur' 'Charmander' 'Bulbasaur' 'Charmander'
 'Bulbasaur' 'Bulbasaur' 'Bulbasaur' 'Charmander' 'Bulbasaur' 'Bulbasaur'
 'Charmander' 'Bulbasaur' 'Charmander' 'Charmander' 'Bulbasaur'
 'Charmander' 'Bulbasaur' 'Charmander' 'Charmander' 'Bulbasaur'
 'Charmander' 'Bulbasaur' 'Bulbasaur' 'Charmander' 'Bulbasaur'
 'Charmander' 'Bulbasaur' 'Pikachu' 'Charmander' 'Charmander' 'Pikachu'
 'Charmander' 'Charmander' 'Pikachu' 'Bulbasaur' 'Bulbasaur' 'Pikachu'
 'Charmander' 'Bulbasaur' 'Pikachu' 'Bulbasaur' 'Bulbasaur' 'Bulbasaur'
 'Charmander' 'Charmander' 'Charmander' 'Charmander' 'Bulbasaur'
 'Bulbasaur' 'Pikachu' 'Bulb

In [38]:
# print(test)

In [39]:
from sklearn.neighbors import KNeighborsClassifier

In [40]:
knn = KNeighborsClassifier(n_neighbors=3)

In [41]:
knn.fit(X, labels)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [42]:
sol = knn.predict(x)

In [43]:
print(sol)

['Bulbasaur' 'Charmander' 'Bulbasaur' 'Charmander' 'Pikachu' 'Pikachu'
 'Pikachu' 'Bulbasaur' 'Bulbasaur' 'Charmander' 'Bulbasaur' 'Bulbasaur'
 'Bulbasaur' 'Bulbasaur' 'Charmander' 'Bulbasaur' 'Charmander'
 'Charmander' 'Pikachu' 'Charmander' 'Pikachu' 'Bulbasaur' 'Charmander'
 'Bulbasaur' 'Charmander' 'Charmander' 'Charmander' 'Bulbasaur' 'Pikachu'
 'Pikachu' 'Pikachu' 'Charmander' 'Charmander' 'Bulbasaur' 'Pikachu'
 'Charmander' 'Bulbasaur' 'Bulbasaur' 'Charmander' 'Bulbasaur' 'Bulbasaur'
 'Pikachu' 'Pikachu' 'Bulbasaur' 'Charmander' 'Bulbasaur' 'Charmander'
 'Bulbasaur' 'Charmander' 'Charmander' 'Pikachu' 'Charmander' 'Pikachu'
 'Bulbasaur' 'Charmander' 'Bulbasaur' 'Bulbasaur' 'Pikachu' 'Pikachu'
 'Pikachu' 'Charmander' 'Pikachu' 'Charmander' 'Charmander' 'Pikachu'
 'Pikachu' 'Bulbasaur' 'Pikachu' 'Pikachu' 'Bulbasaur' 'Bulbasaur'
 'Pikachu' 'Bulbasaur' 'Bulbasaur' 'Charmander' 'Charmander' 'Bulbasaur'
 'Pikachu' 'Pikachu' 'Bulbasaur' 'Pikachu' 'Charmander' 'Charmander'
 'Bulbasaur'

In [44]:
with open('Sample_Submission.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    n = test.shape[0]
    writer.writerow(["ImageId","NameOfPokemon"])
    for i in range(n):
        l = [test[i][0],lab[i]]
        writer.writerow(l)
    csvFile.close()